[project]
name = "pxollyapi"
version = "0.1.0"
description = "Клиент для взаимодействия с API чат менеджера Pxolly"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "niquests>=3.15.2",
    "pydantic>=2.12.5",
]
